### ISSUE TITLE
script and support directory location anomaly

### ISSUE THREAD

**Issue by Dials-Mavis** [rtrouton/create_os_x_vm_install_dmg#2]
When the script is run in the same directory as the **support** directory it returns the following error:

> -- /Users/my_home/support/First Boot Package Install.pkg not found! This is needed for the OS to install properly, exiting..
> -- The script is expecting the following:
> -- A. That a first boot installer package is stored in /Users/my_home/support.
> -- B. That the first boot installer package is named as follows: First Boot Package Install.pkg

I met the 2nd condition (B) but the first (A) is confusing as moving the **support** directory to my_home folder allows the script to run without error, however I followed the documented pre-requisite below:

> Pre-requisites: 
> 1. This script and the associated support directory. This script and the support directory must be both stored in the same directory in order for the script to work properly.

**Comment by rtrouton** [comment]
An assumption of the script is that you're doing this:

cd /path/to/create_os_x_vm_install_dmg_folder

Then running the script like this:

sudo ./create_os_x_vm_install_dmg.sh "/path/to/Install OS X Yosemite / Mavericks / Mountain Lion / Lion.app" /path/to/output/directory

From your report, it sounds like you did not change directory to /path/to/create_os_x_vm_install_dmg_folder. Instead, your location in Terminal was in your home folder. 

The script is doing a relative location lookup for the "support" directory, so when it didn't find it, you got the error. In turn, the error used your current location and told you to put the support directory there in order to successfully run the script. That allowed the script to successfully complete.

**Comment by Dials-Mavis** [comment]
thanks for clarifying, that makes perfect sense to me now and I'm not sure why I didn't think of that obvious logic in the first place. thanks again for this great tool.
